name: Test

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: Colin

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    - run: |
        echo "Hi there ${{ inputs.name }}"
      if: inputs.name == 'Colin'
  
    - run: |
        echo "Also hi there ${{ inputs.name }}"
      if: ${{ inputs.name == join(fromJson('[":", "test", ":", "Colin]'), '') }}
  
